mcp:
  dbs:
    datasources:
      - id: mysql1
        description: MySQL主数据库
        type: mysql
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: root
        sqlExecutionType: READ_WRITE
      - id: postgres1
        description: PostgreSQL只读数据库
        type: postgresql
        url: jdbc:postgresql://localhost:5432/mydb
        username: user
        password: password
        sqlExecutionType: READ_ONLY
